// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// TEMPORARY DEBUG - hapus setelah selesai
supabase.auth.getSession().then(({ data: { session } }) => {
  console.log('=== DEBUG ===');
  console.log('Session:', session);
  console.log('User ID:', session?.user?.id);
  
  supabase.from('community_posts').select('*').then(({ data, error }) => {
    console.log('community_posts data:', data);
    console.log('community_posts error:', error);
  });
});